### ISSUE TITLE
project plan

### ISSUE THREAD

**Issue by hyketwig** [YanlinMa/SpongeBob#2]

**Comment by YanlinMa** [comment]
Checkers.java contains main method and play method:

Main method:
- display string to introduce game
- 1 player vs 2 player (if 1 player, choose level of difficulty)
- executes play method
- after play, display congratulatory message

Play method:
- display original board
- prompts user(s) for piece to move, and coordinate to move to
- reprints board after each user's move
- returns the winning player
- exits method when game is won

**Comment by YanlinMa** [comment]
Board.java stores board data and board related methods
- 2D array called grid
- 6 variables (black square, white square, white square black piece, white square white piece, white square black king, white square white king)

Pieces.java

Separate file for the moves allowed for each type of piece.
Separate file for algorithms when played against the computer.

**Comment by hyketwig** [comment]
to be completed on paper?
